name: Publish website and Upload sitemap and robots

on:
  workflow_dispatch:

jobs:
  generate_sitemap_and_robots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install yargs
        shell: bash
        run: npm install yargs

      - name: Download sitemap.xml and robots.txt
        shell: bash
        env:
          BASE_DOMAIN: "https://staging-webflow.deriv.com"
        run: |
          curl -O $BASE_DOMAIN/sitemap.xml -O $BASE_DOMAIN/robots.txt

      - name: Generate Sitemap and Robots.txt
        uses: ./.github/actions/generate_sitemap_and_robots
        with:
          main_domain: "https://deriv.com"

      - name: Upload to R2
        uses: ./.github/actions/upload_to_r2
        with:
          r2_account_id: ${{ secrets.R2_ACCOUNT_ID }}
          r2_access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2_bucket_name: ${{ secrets.R2_BUCKET_NAME }}
